name: Ap-Overseer
main: net.cccm5.ApOverseer.OverseerMain
version: 1.0
commands:
    playerSpy:
        description: spys on player commands
        permission: ApOverseer.playerSpy
        usage: /playerspy
permissions:
    ApOverseer.playerSpy:
        description: Allows users to spy on players
    ApOverseer.consoleSpy:
        description: Allows users to spy on console log
