name: Ap-Overseer
main: net.cccm5.ApOverseer.OverseerMain
version: 1.0
commands:
    commandSpy:
        description: spys on player commands
        permission: ApOverseer.commandSpy
        usage: /commandSpy
permissions:
    ApOverseer.commandSpy:
        description: Allows users to spy on players
    ApOverseer.consoleSpy:
        description: Allows users to spy on console log
